---
- hosts: all
  user: vagrant
  tasks:
  - name: Update APT package cache
    apt: update_cache=yes
  - name: Installing required packages
    action: apt name={{item}}
    with_items:
      - git
      - nodejs
