---
- hosts: all
  sudo: yes

  tasks:
  - name: Update APT package cache
    apt: update_cache=yes
  - name: Ensure that Postgres packanges are installed
    action: apt name={{item}}
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2

- hosts: all
  sudo: yes
  sudo_user: postgres

  tasks:
    - name: Ensure DB user is ready to go
      postgresql_user: name=styler password=qwerty role_attr_flags=CREATEDB,SUPERUSER

    - name: Create Development, Production and Test databases
      action: postgresql_db name={{item}}
      with_items:
        - freshstyle_development
        - freshstyle_test
        - freshstyle_production

    - name: Ensure user has access to databases
      action: postgresql_user db={{item}} name=styler password=qwerty priv=ALL
      with_items:
        - freshstyle_development
        - freshstyle_test
        - freshstyle_production
